"  ---- PLUGINS
" Install vim-plug:
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

" prevent polyglot from overwriting markdown
" must be before plug#begin
let g:polyglot_disabled = ['markdown']

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-commentary'
call plug#end()


" ----- SOURCES
source ~/.vim/functions.vim " functions and autocommands
source ~/.vim/mappings.vim

" ----- SETTINGS
filetype indent on
filetype on
filetype plugin on
syntax on

" set number
" set relativenumber
set autowrite           " autosave when changing
set belloff=all
set cmdheight=1         " avoid HitEnter prompts
set encoding=utf-8
set hidden              " when switching buffers
set history=100
set hlsearch
set icon
set ignorecase
set incsearch           " highlight search while typing
set nobackup            " more risky, but cleaner
set nocompatible
set nofixendofline      " prevent silent fixing by vim
set nonumber
set noswapfile
set shortmess=aoOtIF    " avoid HitEnter prompts
set showmatch
set showmode
set ttyfast             " faster scrolling

set foldenable
set laststatus=2
set listchars=space:*,trail:*,nbsp:*,extends:>,precedes:<,tab:\|>
set nofixendofline      " better ascii friendly listchars
set noruler
set path+=**
set statusline+=%*\ %<%.60F%*                 " path, trunc to 80 length
set statusline+=%*\ %l:%c%*                   " current line and column
set statusline+=%*\ %p%%%*                    " percentage
set statusline+=\ [%{strlen(&ft)?&ft:'none'}] " filetype
set statusline=
set wrapscan

set autoindent
set expandtab       " replace tabs with spaces
set linebreak
set shiftwidth=2
set smartindent
set smarttab
set softtabstop=2
set tabstop=2
set textwidth=72
set wildignorecase
set wildmenu        " Better command search

hi! link netrwMarkFile Search
let g:netrw_altv = 1
let g:netrw_banner = 0
let g:netrw_browse_split = 4
let g:netrw_fastbrowse = 0
let g:netrw_keepdir = 0
let g:netrw_list_hide = '\(^\|\s\s\)\zs\.\S\+' " dotfiles
let g:netrw_liststyle=3
let g:netrw_winsize = 25

" ----- Colors

" hi Conceal guibg=NONE
" let base16colorspace=256  " Access colors present in 256 colorspace
set background=dark
set termguicolors

" from github.com/lifepillar/vim-gruvbox8
colorscheme gruvbox8_hard

" Copied and made changes to vim-monotone
" github.com/Lokaltog/vim-monotone
" colorscheme monotone
