#!/usr/bin/env bash

THISDIR=$(dirname $(readlink -f $0))

ln -svf $THISDIR/vimrc $HOME/.vimrc

curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
ln -svf $THISDIR/vim/ftplugin $HOME/.vim/

