#!/usr/bin/env sh

THISDIR=$(dirname $(readlink -f $0))
ln -svf $THISDIR/vimrc $HOME/.vimrc
curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
ln -svf $THISDIR/vim/mappings.vim $HOME/.vim/mappings.vim
ln -svf $THISDIR/vim/functions.vim $HOME/.vim/functions.vim

