#!/usr/bin/env sh
# got it from github.com/rwxrob
loc=$(curl -o /dev/null -sIw "%{redirect_url}" 'https://github.com/jgm/pandoc/releases/latest')
vers=${loc##*/}
deb=pandoc-$vers-1-amd64.deb
uri=${loc%/tag*}/download/$vers/$deb
echo "Downloading $uri"
curl -sL "$uri" -o "/tmp/$deb"
echo "Installing /tmp/$deb"
dpkg -i "/tmp/$deb"
