#! /usr/bin/bash

sudo apt install git npm python3.10-venv python3-pip ripgrep shellcheck tmux tree tzdata vim w3m yarn

curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage 
sudo mv nvim.appimage /usr/bin/nvim

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
nvm install node
