#!/usr/bin/bash

# .bash_aliases

# ----- SHORTCUTS
alias                               \
  vi=nvim                           \
  arc="vi ~/.config/bash/aliases"   \
  brc="vi ~/.bashrc"                \
  trc="vi ~/.tmux.conf"             \
  vrc="vi ~/.vimrc"                 \
  nrc="vi ~/.config/nvim/lua"       \
  wrc="vi ~/.w3m/config"            \
  g="lazygit"                       \
  k="clear"                         \
  web="w3m -B"

# ----- AUTO-OPTIONS
alias                               \
  rg="rg -i -C 3"                   \
  grep="grep -i --colour=auto"      \
  egrep="egrep -i --colour=auto"    \
  fgrep="fgrep -i --colour=auto"    \
  curl="curl -L"                    \
  ls="ls -h --color=auto"           \
  cp="cp -iv"                       \
  mv="mv -iv"                       \
  rm="rm -v"                        \
  mkd="mkdir -pv"

# ----- WORKSPACES
alias                               \
  repos='cd ${REPOS} && ls -A'      \
  mome='cd ${MOME} && ls -A'        \
  lab='cd ${REPOS}/lab && ls -A'

# ----- COPILOT
alias                               \
  ghce='gh copilot explaing'        \
  ghcs='gh copilot suggest'         

