#!/usr/bin/bash
# .bashrc

# case $- in
# *i*) ;; #interactive
# *( return ;;
# esac

# source global definitions
[ -f /etc/bash.bashrc ] && . /etc/bash.bashrc

# ----- DEFAULTS
if [[ $TERM == xterm ]]; then
    TERM=xterm-256color
fi

if [[ $TERM == screen ]]; then
    TERM=screen-256color
fi

set -o vi
export VISUAL=nvim
export EDITOR="$VISUAL"
# Ignore .git directories and cache files
export FZF_DEFAULT_COMMAND="find . -type f -not -path '*/\.git/*' -not -path '*cache*'"
export DOWNLOADS="$HOME/Downloads"

# ----- PATHS
export XDG_CONFIG_HOME=$HOME/.config
export MOME=$HOME/mome
export PROJECTS=$HOME/tmp
export REPOS=$HOME/repos
export PATH="$PATH:/opt/nvim-linux64/bin"
export PATH="$PATH:$HOME/.local/go/bin"
if ! [[ "$PATH" =~ $HOME/.local/bin:$HOME/bin: ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH=$PATH

# see man bash
#CDPATH=".:$HOME/repos/hikib/lab"

# ----- HISTORY
export HISTCONTROL=ignoreboth
export HISTSIZE=5000
export HISTFILESIZE=10000

# ----- PROMPT
# search for: ANSI color codes
__ps1(){
  declare GITBRANCH
  GITBRANCH="$(git branch --show-current 2>/dev/null)"
  test -n "$GITBRANCH" && GITBRANCH=".$GITBRANCH" # show dot
  local U="\[\e[00;38;5;255m\]\u"  # user
  local H="\[\e[00;38;5;180m\]\h"  # machine
  local D="\[\e[00;38;5;255m\]\W"  # directory
  local B="\[\e[00;38;5;180m\]$GITBRANCH"
  local S="\[\e[00;38;5;203m\]$"
  local TEXTRESET="\[\e[00;38;5;223m"
  PS1="$U.$H $D$B \n$S $TEXTRESET"
}
PROMPT_COMMAND="__ps1"

# ----- OTHER SOURCES
[ -x "$(command -v dircolors)" ] && [ -r ~/.config/bash/colors ] && eval "$(dircolors ~/.config/bash/colors)"
[ -r  "$HOME/.config/bash/aliases" ] && . "$HOME/.config/bash/aliases"
[ -r  "$HOME/.config/bash/inputrc" ] && bind -f "$HOME/.config/bash/inputrc"

# ----- MANAGE NODE VERSION FOR NVIM/LSP/MASON
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
