#!bash
# .bashrc

# case $- in
# *i*) ;; #interactive
# *( return ;;
# esac


# source global definitions
[ -f /etc/bashrc ] && . /etc/bashrc

# ----- DEFAULTS
if [[ $TERM == xterm ]]; then
    TERM=xterm-256color
fi

if [[ $TERM == screen ]]; then
    TERM=screen-256color
fi

set -o vi
export VISUAL=vim
export EDITOR="$VISUAL"
# Ignore .git directories and cache files
export FZF_DEFAULT_COMMAND="find . -type f -not -path '*/\.git/*' -not -path '*cache*'"

# ----- GO
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export CGO_ENABLED=1

# ----- PATHS
export MOME=$HOME/mome          # Modus Operandi
export REPOS=$HOME/repos
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH=$PATH
export PATH=$PATH:$GOBIN
# export PATH

# ----- HISTORY
export HISTCONTROL=ignoreboth
export HISTSIZE=5000
export HISTFILESIZE=10000

# ----- PROMPT
# search for: ANSI color codes
__ps1(){
  local GITBRANCH="$(git branch --show-current 2>/dev/null)"
  test -n "$GITBRANCH" && GITBRANCH=".$GITBRANCH" # show dot
  local U="\[\e[00;38;5;255m\]\u"  # user
  local H="\[\e[00;38;5;180m\]\h"  # machine
  local D="\[\e[00;38;5;255m\]\W"  # directory
  local B="\[\e[00;38;5;180m\]$GITBRANCH"
  local S="\[\e[00;38;5;203m\]$"
  local TEXTRESET="\[\e[00;38;5;223m"
  PS1="$U.$H $D$B \n$S $TEXTRESET"
}
PROMPT_COMMAND="__ps1"

# ----- FUNCTIONS
# use functions when cd is needed
clone ()
{
  # thx to rwxrob
  local repo="$1" user;
  local repo="${repo#https://github.com/}";
  local repo="${repo#git@github.com:}";
  if [[ $repo =~ / ]]; then
      user="${repo%%/*}";
  else
      user="$GITUSER";
      [[ -z "$user" ]] && user="$USER";
  fi;
  local name="${repo##*/}";
  local userd="$REPOS/github.com/$user";
  local path="$userd/$name";
  [[ -d "$path" ]] && cd "$path" && return;
  mkdir -p "$userd";
  cd "$userd";
  echo gh repo clone "$user/$name" -- --recurse-submodule;
  gh repo clone "$user/$name" -- --recurse-submodule;
  cd "$name"
}

# ----- OTHER SOURCES
[ -r ~/.dir_colors ] && eval $(dircolors ~/.dir_colors)
[ -r ~/.bash_aliases ] && source ~/.bash_aliases
[ -f ~/.cargo/env ] && source $HOME/.cargo/env # rust
. "$HOME/.cargo/env"
