# .bash_aliases

alias \
  python=python3                                                  \
  pyvenv="python -m venv .env && source .env/bin/activate"


# TODO: switch to bash script for gitbash
alias \
  ?="searchweb -page=duck "         \
  ord="searchweb -page=ordnet "     \
  korp="searchweb -page=korpus "    \
  tysk="searchweb -page=tysk "      \
  yt="searchweb -page=youtube "     \
  github="searchweb -page=github "  \
  twitch="searchweb -page=twitch "


alias \
  vrc="vim ~/.vimrc"            \
  brc="vim ~/.bash_profile"     \
  vi=vim


alias \
  repos="cd ${REPOS} && ls -A"


alias \
  k="clear"                      \
  cp="cp -iv"                    \
  mv="mv -iv"                    \
  rm="rm -v"                     \
  mkd="mkdir -pv"

