#!/usr/bin/env sh

THISDIR=$(dirname $(readlink -f $0))

ln -svf $THISDIR/bashrc $HOME/.bashrc
ln -svf $THISDIR/bash_profile $HOME/.bash_profile
ln -svf $THISDIR/bash_aliases $HOME/.bash_aliases
ln -svf $THISDIR/dir_colors $HOME/.dir_colors

