#!/usr/bin/env sh

THISDIR=$(dirname $(readlink -f $0))

if [ "$OSTYPE" = "linux-gnu" ];then
  ln -svf $THISDIR/snippets $HOME/.snippets
else
  echo "ERROR"
  echo "Use the setup-gitbash.ps1 script if you're on Windows!"
fi


